- hosts: server
  remote_user: root
  tasks:
      - name: install python deps
        yum: name=git,python-devel,python,python-virtualenv,python-setuptools
      - name: install lib deps
        yum: name=cyrus-sasl-devel,openldap-devel,libxml2-devel,libxslt-devel
      - name: install mysql deps
        yum: name=mariadb,mariadb-server,mariadb-devel
      - name: install npm
        yum: name=npm
      - name: install bower
        command: npm install -g bower
        args:
            creates: /usr/bin/bower
      - name: install supervisor
        yum: name=supervisor
      - name: create user
        user: name=mvalleychallenge shell=/bin/bash
      - name: checkout app
        git: repo=https://github.com/kagesenshi/yet-another-gameoflife-sim.git
             dest=/opt/app
             update=yes
      - name: chown
        command: chown -R mvalleychallenge:mvalleychallenge /opt/app

      - stat: path=/opt/app/bin/buildout
        register: cl

      - name: build app
        command: sudo -u mvalleychallenge ./build.sh
        args:
            chdir: /opt/app
            creates: /opt/app/bin/pserve

      - stat: path=/opt/app/bin/develop
        register: develop_script

      - name: run buildout if already exists
        command: sudo -u mvalleychallenge ./bin/buildout -vvv
        when: cl.stat.exists
        args:
            chdir: /opt/app


      - name: update sources
        command: ./bin/develop up -f
        when: develop_script.stat.exists
        args:
            chdir: /opt/app


      - name: start mysql
        service: name=mariadb state=restarted enabled=yes

      - name: create database
        command: /opt/app/createdb.sh
        args:
            creates: /var/lib/mysql/gameoflife/

      - name: install supervisord config
        copy: src=supervisord.ini dest=/etc/supervisord.d/mvalleychallenge.ini
      - name: start supervisord on boot
        service: name=supervisord state=restarted enabled=yes
